# Generated by Django 5.1.1 on 2024-10-04 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhanvien', '0002_alter_user_options_user_is_admin_user_is_employee_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('position', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='position',
            field=models.CharField(default='admin', max_length=50),
        ),
    ]
