# Generated by Django 5.1.3 on 2024-11-17 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhanvien', '0010_contract_end_date_contract_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='renewal_pending',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contract',
            name='renewal_request_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
