# Generated by Django 5.1.3 on 2024-11-18 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhanvien', '0011_contract_renewal_pending_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='contract_file',
        ),
        migrations.AddField(
            model_name='contract',
            name='approval_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='approval_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('Active', 'Đang làm việc'), ('Expired', 'Hết hạn'), ('Renewed', 'Đã gia hạn'), ('Terminated', 'Đã kết thúc')], default='Active', max_length=50),
        ),
    ]
