# Generated by Django 5.1.3 on 2024-12-12 00:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhanvien', '0013_alter_contract_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('Pending', 'Chưa bắt đầu'), ('In Progress', 'Đang thực hiện'), ('Completed', 'Đã hoàn thành'), ('Delayed', 'Bị trì hoãn')], default='Pending', max_length=20)),
                ('progress', models.PositiveIntegerField(default=0)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='nhanvien.employee')),
            ],
        ),
    ]
