# Generated by Django 4.2.17 on 2025-01-03 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhanvien', '0019_employee_late_penalty'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='standard_days',
            field=models.IntegerField(default=22),
        ),
    ]
