# Generated by Django 4.2.17 on 2025-01-03 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhanvien', '0020_employee_standard_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='late_penalty',
            field=models.DecimalField(decimal_places=0, default=50000, max_digits=10),
        ),
    ]
