# Generated by Django 4.2.17 on 2025-01-03 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhanvien', '0022_alter_employee_hourly_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='net_salary_after_tax',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
    ]
